jenkins:
  systemMessage: "Hello! Welcome to my Jenkins instance :)"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "jigglypuff"
          password: ${PASSWORD}
          name: "Jigglypuff"
          email: "tkt@tkt.com"

jobs:
  - file: /var/jenkins_home/job_dsl.groovy
